use std::collections::{HashMap, HashSet};

use crate::ast::{Item, Program, Type};

/// Generate the C header for a shared-library build: `XzStr`/`XzBytes`, every
/// declared `@cstruct` record (in dependency order), and a prototype for each
/// `@export` function. The front end has already rejected anything that is not
/// C-representable, so this is a faithful transcription of the ABI
/// (docs/10-ffi-interop.md).
pub fn generate_c_header(program: &Program) -> String {
    let mut cstruct: HashSet<String> = HashSet::new();
    let mut records: HashMap<String, &crate::ast::RecordDecl> = HashMap::new();
    for item in &program.items {
        if let Item::Record(r) = item
            && r.cstruct
        {
            cstruct.insert(r.name.clone());
            records.insert(r.name.clone(), r);
        }
    }

    let mut out = String::new();
    out.push_str("/* Generated by `xz build --shared`. Do not edit. */\n");
    out.push_str(
        "/*\n * ABI ownership (docs/10-ffi-interop.md): every parameter is valid only for\n * the duration of the call, and a returned pointer (XzStr, XzBytes, void*, or\n * a struct containing one) is retained by the library and must not be freed by\n * the caller. An `@export` function cannot transfer ownership either way.\n */\n",
    );
    out.push_str("#ifndef XZ_LIBXZ_H\n#define XZ_LIBXZ_H\n\n");
    out.push_str("#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n\n");
    out.push_str("typedef struct XzStr { const char* ptr; size_t len; } XzStr;\n");
    out.push_str("typedef struct XzBytes { const uint8_t* ptr; size_t len; } XzBytes;\n\n");

    let mut names: Vec<&String> = records.keys().collect();
    names.sort();
    let mut emitted: HashSet<String> = HashSet::new();
    for name in names {
        emit_record(&mut out, name, &records, &cstruct, &mut emitted);
    }
    if !records.is_empty() {
        out.push('\n');
    }

    for item in &program.items {
        if let Item::Func(f) = item {
            if !f.exported {
                continue;
            }
            let ret = match &f.ret {
                Some(t) => c_type(t, &cstruct).unwrap_or_else(|| "void".to_string()),
                None => "void".to_string(),
            };
            let params: Vec<String> = f
                .params
                .iter()
                .map(|p| {
                    let ct = c_type(&p.ty, &cstruct).unwrap_or_else(|| "void*".to_string());
                    // A `mut` parameter is in/out: it crosses as a pointer to
                    // the value type (docs/04-memory-model.md, docs/10).
                    if p.mutable {
                        format!("{}* {}", ct, p.name)
                    } else {
                        format!("{} {}", ct, p.name)
                    }
                })
                .collect();
            let plist = if params.is_empty() { "void".to_string() } else { params.join(", ") };
            out.push_str(&format!("{} {}({});\n", ret, f.name, plist));
        }
    }

    out.push_str("\n#endif /* XZ_LIBXZ_H */\n");
    out
}

fn emit_record(
    out: &mut String,
    name: &str,
    records: &HashMap<String, &crate::ast::RecordDecl>,
    cstruct: &HashSet<String>,
    emitted: &mut HashSet<String>,
) {
    if !emitted.insert(name.to_string()) {
        return;
    }
    let Some(rec) = records.get(name) else {
        return;
    };
    for f in &rec.fields {
        if let Some(dep) = named_cstruct(&f.ty, cstruct) {
            emit_record(out, &dep, records, cstruct, emitted);
        }
    }
    let mut fields = String::new();
    for f in &rec.fields {
        let ct = c_type(&f.ty, cstruct).unwrap_or_else(|| "void*".to_string());
        fields.push_str(&format!("    {} {};\n", ct, f.name));
    }
    out.push_str(&format!("typedef struct {} {{\n{}}} {};\n", name, fields, name));
}

/// The C type name for a checked C-representable Xz type. `None` is only
/// reached if the front end let an unrepresentable type through; callers fall
/// back to `void*`.
fn c_type(ty: &Type, cstruct: &HashSet<String>) -> Option<String> {
    let name = match ty {
        Type::Named(n, args) => {
            if !args.is_empty() {
                return None;
            }
            n
        }
        Type::NamedPlain(n) => n,
        Type::Union(_) => return None,
    };
    let c = match name.as_str() {
        "Bool" => "bool",
        "Int" => "int64_t",
        "usize" => "uint64_t",
        "Float" => "double",
        "Char" => "char",
        "Str" => "XzStr",
        "Bytes" => "XzBytes",
        "Ptr" => "void*",
        "Unit" => "void",
        other => {
            if cstruct.contains(other) {
                other
            } else {
                return None;
            }
        }
    };
    Some(c.to_string())
}

fn named_cstruct(ty: &Type, cstruct: &HashSet<String>) -> Option<String> {
    let name = match ty {
        Type::Named(n, args) if args.is_empty() => n,
        Type::NamedPlain(n) => n,
        _ => return None,
    };
    if cstruct.contains(name) {
        Some(name.clone())
    } else {
        None
    }
}
