use std::collections::{HashMap, HashSet};

use crate::ast::{Item, Param, Program, RecordDecl, Type};

/// A C ABI function signature the generated wrapper binds: an `@export func`
/// (via `xz bind`) or an `extern func` (via `xz pkg gen`).
type Signature<'a> = (&'a str, &'a [Param], &'a Option<Type>);

/// Generate a Python `ctypes` wrapper for a shared-library build. It mirrors
/// the C header: `XzStr`/`XzBytes`, every declared `@cstruct` record (in
/// dependency order), and a typed binding for each `@export` function. The
/// front end has already rejected anything that is not C-representable, so
/// this is a faithful transcription of the ABI (docs/10-ffi-interop.md).
pub fn generate_python_bindings(program: &Program) -> String {
    let sigs = exported_signatures(program);
    let lib = "os.path.join(os.path.dirname(os.path.abspath(__file__)), \"libXz.so\")";
    emit_module(
        program,
        lib,
        "# Generated by `xz bind --lang python`. Do not edit.",
        &sigs,
    )
}

/// Generate a Python `ctypes` wrapper for a `.xzint` interface file: every
/// `extern` function is bound against the C library `lib` (loaded by name, not
/// as a sibling file), and every `@cstruct` record becomes a `ctypes.Structure`
/// (docs/10-ffi-interop.md).
pub fn generate_python_interface_bindings(program: &Program, lib: &str) -> String {
    let sigs = extern_signatures(program);
    let lib_expr = quote(lib);
    emit_module(
        program,
        &lib_expr,
        "# Generated by `xz pkg gen --lang python`. Do not edit.",
        &sigs,
    )
}

fn exported_signatures(program: &Program) -> Vec<Signature<'_>> {
    program
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Func(f) if f.exported => Some((f.name.as_str(), f.params.as_slice(), &f.ret)),
            _ => None,
        })
        .collect()
}

fn extern_signatures(program: &Program) -> Vec<Signature<'_>> {
    program
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Extern(e) => Some((e.name.as_str(), e.params.as_slice(), &e.ret)),
            _ => None,
        })
        .collect()
}

/// Render a Rust `&str` as a double-quoted Python string literal. The
/// interface library name is user-supplied and lands in generated source, so
/// quotes and backslashes are escaped rather than interpolated raw.
fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

fn emit_module(program: &Program, lib_expr: &str, header: &str, sigs: &[Signature<'_>]) -> String {
    let mut cstruct: HashSet<String> = HashSet::new();
    let mut records: HashMap<String, &RecordDecl> = HashMap::new();
    for item in &program.items {
        if let Item::Record(r) = item
            && r.cstruct
        {
            cstruct.insert(r.name.clone());
            records.insert(r.name.clone(), r);
        }
    }

    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    out.push_str("import ctypes\nimport os\n\n");
    out.push_str(&format!("_lib = ctypes.CDLL({})\n\n", lib_expr));
    out.push_str("class XzStr(ctypes.Structure):\n");
    out.push_str("    _fields_ = [(\"ptr\", ctypes.c_char_p), (\"len\", ctypes.c_size_t)]\n\n");
    out.push_str("class XzBytes(ctypes.Structure):\n");
    out.push_str("    _fields_ = [(\"ptr\", ctypes.POINTER(ctypes.c_uint8)), (\"len\", ctypes.c_size_t)]\n\n");

    let mut names: Vec<&String> = records.keys().collect();
    names.sort();
    let mut emitted: HashSet<String> = HashSet::new();
    for name in names {
        emit_record(&mut out, name, &records, &cstruct, &mut emitted);
    }

    for (name, params, ret) in sigs {
        let argtypes: Vec<String> = params
            .iter()
            .map(|p| py_type(&p.ty, &cstruct).unwrap_or_else(|| "ctypes.c_void_p".to_string()))
            .collect();
        let restype = match ret {
            Some(t) => py_type(t, &cstruct).unwrap_or_else(|| "None".to_string()),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "_lib.{}.argtypes = [{}]\n",
            name,
            argtypes.join(", ")
        ));
        out.push_str(&format!("_lib.{}.restype = {}\n", name, restype));
        out.push_str(&format!("{} = _lib.{}\n\n", name, name));
    }

    out
}

fn emit_record(
    out: &mut String,
    name: &str,
    records: &HashMap<String, &RecordDecl>,
    cstruct: &HashSet<String>,
    emitted: &mut HashSet<String>,
) {
    if !emitted.insert(name.to_string()) {
        return;
    }
    let Some(rec) = records.get(name) else {
        return;
    };
    for f in &rec.fields {
        if let Some(dep) = named_cstruct(&f.ty, cstruct) {
            emit_record(out, &dep, records, cstruct, emitted);
        }
    }
    let mut fields: Vec<String> = vec![];
    for f in &rec.fields {
        let ct = py_type(&f.ty, cstruct).unwrap_or_else(|| "ctypes.c_void_p".to_string());
        fields.push(format!("(\"{}\", {})", f.name, ct));
    }
    out.push_str(&format!("class {}(ctypes.Structure):\n", name));
    out.push_str(&format!("    _fields_ = [{}]\n\n", fields.join(", ")));
}

/// The `ctypes` expression for a checked C-representable Xz type. `None` is
/// only reached if the front end let an unrepresentable type through; callers
/// fall back to `ctypes.c_void_p`.
fn py_type(ty: &Type, cstruct: &HashSet<String>) -> Option<String> {
    let name = match ty {
        Type::Named(n, args) => {
            if !args.is_empty() {
                return None;
            }
            n
        }
        Type::NamedPlain(n) => n,
        Type::Union(_) => return None,
    };
    let c = match name.as_str() {
        "Bool" => "ctypes.c_bool",
        "Int" => "ctypes.c_int64",
        "usize" => "ctypes.c_uint64",
        "Float" => "ctypes.c_double",
        "Char" => "ctypes.c_char",
        "Str" => "XzStr",
        "Bytes" => "XzBytes",
        "Ptr" => "ctypes.c_void_p",
        "Unit" => "None",
        other => {
            if cstruct.contains(other) {
                other
            } else {
                return None;
            }
        }
    };
    Some(c.to_string())
}

fn named_cstruct(ty: &Type, cstruct: &HashSet<String>) -> Option<String> {
    let name = match ty {
        Type::Named(n, args) if args.is_empty() => n,
        Type::NamedPlain(n) => n,
        _ => return None,
    };
    if cstruct.contains(name) {
        Some(name.clone())
    } else {
        None
    }
}
